batch_size: 1
checkpoint_time: 100
encodings: true
epoch: 0
epochs_per_mip: 2
feature_maps:
- 12
- 18
- 24
- 30
- 36
- 42
- 48
- 54
gamma: 0.1
gamma_step: 30
gpus: '0'
height: 8
initialized_list:
- true
- true
- true
- true
- true
- true
- true
- true
iteration: 0
lambda1: 250000000.0
levels: !!python/object/apply:builtins.slice
- null
- null
- null
log_time: 1
lr: 0.0005
name: 111119_nk_vf_30_faster_base
num_epochs: 1000000000
num_samples: null
penalty: lap
plan: all
repeats: 1
seed: null
skip_aug: true
start_lr: 0.0005
supervised: false
training_set_path: !!python/object/apply:pathlib.PosixPath
- /
- usr
- people
- nkemnitz
- src
- SEAMLeSS
- test.h5_train_mip2.h5
validation_set_path: null
vis_time: 50
wd: 0